# Generated by Django 4.2.14 on 2024-07-30 18:49

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to=core.models.upload_to)),
                ('comments', models.TextField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Review Request',
                'verbose_name_plural': 'Review Requests',
            },
        ),
        migrations.CreateModel(
            name='PageResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('service', models.CharField(max_length=100)),
                ('details', models.JSONField()),
                ('review_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reviewrequest')),
            ],
            options={
                'verbose_name': 'Page Result',
                'verbose_name_plural': 'Page Results',
                'unique_together': {('review_request', 'page_number', 'service')},
            },
        ),
    ]
