# Generated by Django 4.2.14 on 2024-10-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pageresult_flaged_reviewrequest_bottom_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='output',
            field=models.FileField(blank=True, null=True, upload_to='output/'),
        ),
    ]
